name: Pull Request Commenter
on: pull_request
jobs:
  auto-pr-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: scottlow/pr-comment-action@master
      with:
        message: |-
          Hello, world!\n
          Testing to see if **markdown** is supported!\n
          Let's try a checklist!\n
          - [] Have you read about Privacy?\n
          - [] Did you implement some best practices?
          - [x] This one is checked!
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        assignees: '["scottlow"]'
