name: Task Completion Checker
on: 
  issue_comment
jobs:
  task-completion-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: scottlow/task-complete-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
