name: Task Completion Checker
on: 
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  task-completion-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: scottlow/task-comment-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
