name: Task Completion Checker
on: 
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  task-completion-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: scottlow/task-comment-action@master
      with:
        message: |-
          Hello, world!
          Testing to see if **markdown** is supported!
          Let's try a checklist!
          - [ ] Have you read about Privacy?
          - [ ] Did you implement some best practices?
          - [x] This one is checked!
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        assignees: '["scottlow"]'
